Updated google sign-in method for new GoogleSignIn 7.0
TheraForge/OTFMagicBox pull request #6
Opened 2023-05-05 02:41 UTC by tfmart

I tried running this SDK on my machine and, upon installing the third-party dependencies with `pod install`, some errors showed up on the Google Sign-In method on the Onboarding part. Currently, the Podfile is not specifying an version of the `GoogleSignIn` library, so it attempted to install the latest version available.

[Upon reviewing the changelog for the latest version (7.0) of the GoogleSignIn library](https://github.com/google/GoogleSignIn-iOS/releases/tag/7.0.0), I discovered that the sign-in configuration setup has been moved from the signIn method to a new property of GIDSignIn, and that the method signature has been updated.

This pull request implements the required changes to enable the use of the new properties and methods introduced in version 7.0 of the `GoogleSignIn` library in Magic Box, while preserving all existing rules and functionality.

2023-05-05 02:46 UTC, tfmart commented
If you'd rather keep using the previous major version, you can specify an version for `GoogleSignIn` on this project's Podfile:

```ruby
# Install latest version up to 7.0
pod 'GoogleSignIn','~> 6.2.4'
```

2023-05-19 11:48 UTC, invozeeshan requested changes
Please revert these changes and set the GoogleSignIn pod version to 6.2.2 instead. This version update of GoogleSignIn has been taken care of and will be available in the next release.
Can you please replace the GoogleSingIn pod line with the following line?
pod 'GoogleSignIn', '6.2.2'

2023-05-22 16:54 UTC, tfmart commented
@invozeeshan understood. I'll be able to revert my changes next Wednesday as I'm current away from my laptop. Feel free to close my pull request and implement the changes yourselves if you wish to

Thanks for the update. Take care!

2023-05-23 09:36 UTC, closed without merging

2023-05-23 10:05 UTC, marco-theraforge commented
Thanks @tfmart for opening the PR. We have fixed the release number using the version we previously tested. Moreover, in the next release we plan to add support for the new Google SignIn 7.0.